In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('train.txt',sep=';',header=None, names=['text','emotion'])

In [4]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [5]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [6]:
unique_emotions=df['emotion'].unique()
emotion_numbers={}
i=0
for emo in unique_emotions:
    emotion_numbers[emo]=i
    i+=1

df['emotion']=df['emotion'].map(emotion_numbers)

In [7]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [8]:
df['text']=df['text'].apply(lambda x:x.lower())

In [9]:
 import string
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [10]:
df['text']=df['text'].apply(remove_punc)

In [11]:
def remove_numbers (txt):
    new=""
    for i in txt:
        if not i.isdigit():
            new=new+1
        return new 
    df['text']=df['text'].apply(remove_numbers)

## Removing emojis

In [12]:
def remove_emojis(txt):
    new=""
    for i in txt:
        if i.isascii():
            new+=i
    return new
df['text']=df['text'].apply(remove_emojis)

Removing Stopwords

In [13]:
%pip install nltk

Requirement already satisfied: nltk in /home/siddhu/Desktop/Hello-world/Machine Learning/sklearn-env/lib/python3.10/site-packages (3.9.4)
Requirement already satisfied: joblib in /home/siddhu/Desktop/Hello-world/Machine Learning/sklearn-env/lib/python3.10/site-packages (from nltk) (1.5.3)
Requirement already satisfied: click in /home/siddhu/Desktop/Hello-world/Machine Learning/sklearn-env/lib/python3.10/site-packages (from nltk) (8.4.2)
Requirement already satisfied: regex>=2021.8.3 in /home/siddhu/Desktop/Hello-world/Machine Learning/sklearn-env/lib/python3.10/site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in /home/siddhu/Desktop/Hello-world/Machine Learning/sklearn-env/lib/python3.10/site-packages (from nltk) (4.68.3)
Note: you may need to restart the kernel to use updated packages.

In [14]:
import nltk
nltk.download('popular')

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to /home/siddhu/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /home/siddhu/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular

True

In [15]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [16]:
if "/home/siddhu/nltk_data" not in nltk.data.path:
    nltk.data.path.append("/home/siddhu/nltk_data")

In [17]:
nltk.download('punkt', download_dir="/home/siddhu/nltk_data")
nltk.download('punkt_tab', download_dir="/home/siddhu/nltk_data")
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /home/siddhu/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/siddhu/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /home/siddhu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [18]:
stop_words=set(stopwords.words('english'))
len(stop_words)

198

In [19]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [20]:
def remove(txt):
    words=nltk.word_tokenize(txt)
    cleaned=[]
    for i in words:
        if not i in stop_words:
            cleaned.append(i)
    
    return ' '.join(cleaned)

In [21]:
nltk.data.path.append("/home/siddhu/nltk_data")

In [22]:
df['text']=df['text'].apply(remove)

In [23]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [24]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['text'],df['emotion'],test_size=0.20,random_state=42)

In [26]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [27]:
X_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
15578    feel useful pulpit find ironic often question ...
5746             dried bladders ready day im feeling brave
6395                             feel thrilled matter days
7624     woke morning text mr c declaring walking work ...
15245                                            feel dumb
Name: text, Length: 3200, dtype: object

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [49]:
bow_vectorizer=CountVectorizer()

In [50]:
X_train_bow=bow_vectorizer.fit_transform(X_train)

In [51]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [52]:
X_test_bow=bow_vectorizer.transform(X_test)

In [53]:
X_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 26934 stored elements and shape (3200, 13359)>

In [54]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [55]:
nb_model=MultinomialNB()

In [56]:
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [58]:
pred_bow=nb_model.predict(X_test_bow)

In [59]:
print(accuracy_score(y_test,pred_bow))

0.7678125

In [60]:
pred_bow

array([0, 5, 0, ..., 5, 5, 0], shape=(3200,))

In [61]:
y_test

8756     0
4660     5
6095     0
304      5
8241     0
        ..
15578    5
5746     5
6395     5
7624     5
15245    0
Name: emotion, Length: 3200, dtype: int64

In [62]:
Tfidf_vectorizer=TfidfVectorizer()

In [63]:
X_train_tfidf=Tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf=Tfidf_vectorizer.transform(X_test)

In [64]:
nb_model2=MultinomialNB()
nb_model2.fit(X_train_tfidf,y_train)

MultinomialNB()

In [65]:
y_pred=nb_model2.predict(X_test_tfidf)

In [66]:
print(accuracy_score(y_test,y_pred))

0.6609375

In [67]:
from sklearn.linear_model import LogisticRegression

In [68]:
logistic_model=LogisticRegression(max_iter=1000)

In [69]:
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [70]:
log_pred=logistic_model.predict(X_test_tfidf)

In [71]:
print(accuracy_score(y_test,log_pred))

0.8615625